GET http://localhost:3000/comments HTTP/1.1
###

POST http://localhost:3000/comments HTTP/1.1
content-type: application/json

{
    "text": "third comment",
    "userId": "68512c7a68f9ba98622d4358"
}